### PR TITLE
feat: emit sequence with the package event

### PR DESCRIPTION
**Pull request by FredKSchott**
Hey there! I've loved using this library but had to make one small change to get it to work for my use case. I use the sequence of each "package" event to track how far along in the stream we are, and to pick up where we left off if the program exists/restarts. 

Making this PR in case this would be a useful change for others.

### CODE REVIEW

**Comment by zeke** [comment]
Hi @FredKSchott! I just came across your profile yesterday when @gr2m mentioned that you're working on the pika.dev project. Small world. Does pika use `package-stream`?!

I'm happy to merge this and create a new release, but I have a few questions first:

- Is it possible/easy to add a test for this new behavior?
- Semantically speaking, should this be considered a fix, a feature, or a breaking change? 🤔

**Comment by FredKSchott** [comment]
Hey @zeke, small world indeed! I didn't realize it was you behind this project :D 
sure thing, added a test and updated the README. As far as version, I think either patch or minor would be fine. A minor version bump would be most correct, as it's adding new functionality but not breaking existing functionality.

**Comment by FredKSchott** [comment]
And yes, Pika uses package-stream to keep our internal index (powering both the website and the CDN) in sync, thanks for creating it!

**Comment by zeke** [comment]
Sorry one more thing: Can you document this in the README?

**Comment by FredKSchott** [comment]
I added it to the code snippet in the README, let me know where else you'd like me to document it? Or, feel free to merge and then make any changes on top if that's easier than the back and forth.

**Comment by zeke** [comment]
```
$ np minor

Publish a new version of package-stream (current: 3.0.3)

Commits:
- add gitignore  9c53390
- Merge pull request #8 from FredKSchott/patch-1  e230bc3
- Update readme.md  c81c5b1
- Update test.js  3ac5019
- Emit sequence with the package event  44b7add

Commit Range:
v3.0.3...master


  ✔ Prerequisite check
  ✔ Git
  ↓ Cleanup [skipped]
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ✔ Bumping version using npm
  ✔ Publishing package using npm
  ✔ Pushing tags
  ✔ Creating release draft on GitHub

 package-stream 3.1.0 published 🎉
```

**Comment by zeke** [comment]
Thanks Fred! Happy Friday.

**Pull request merged**
